CREATE TABLE IF NOT EXISTS WEBAPI_PROPERTIES 
(id INTEGER NOT NULL,
jdbc_url VARCHAR(100) NOT NULL,
jdbc_user VARCHAR(25) NOT NULL,
jdbc_pass VARCHAR(25) NOT NULL,
created DATE,
PRIMARY KEY (id));
--PUBLIC.